---
title: "🏠 Overview"
format: 
    html: default
    pdf: default
    docx: default
    rtf: default
---


::: {.columns}
::: {.column width="55%"}
###  Quick Links
- <i class="bi bi-easel"></i> **Blackboard:** [link](https://blackboard.syracuse.edu/")
- <i class="bi bi-pc-display"></i> **Course Drive:** [onedrive link](https://sumailsyr-my.sharepoint.com/:f:/g/personal/jlreilly_syr_edu/Eu4KEF0yXJRDioxxAORsreYBqln2ON75JFA4hx8u6CfVrg?e=kP63Ow)
- <i class="bi bi-journal-text"></i> **Syllabus & Materials:** [right here](https://jacklreilly.github.io/pai721-f25/syllabus)
:::
:::

# Course Information

## Class


<i class="bi bi-geo-alt"></i> Location: Eggers Hall 113 <br>

<i class="bi bi-clock"></i> Time: Tuesday and Thursday, 9:30 AM - 10:50 AM <br>

## Instructor

**Professor Jack Reilly**

**Office**: Eggers 225F

**Office Hours**: Tuesday and Thursday, 11 AM - Noon (drop in) and by appointment.[^oh]

[^oh]: In addition to formal office hours, I have an open door policy - feel free to stop by if you see the door open. I'll also be around after office hours until at least 12:30 each Tuesday and Thursday according to student need.  I also am usually around between 3:30 and 4 Tuesdays and Thursdays and free to meet, but give me a heads up if you plan on coming around at that time so I know to be on the lookout for you - I'm sometimes in another room with another class.

**Zoom Hours**: Friday, 1-3 ([schedule online](https://jacklreilly.github.io/appointments.html))

**Phone**: 315-443-2687 (office)

**e-mail**: <jlreilly@syr.edu>


## Description

Public policy and administration decisions are often difficult and risky because decisions must be made with incomplete and imperfect information. The primary purpose of this course is to introduce the basics of modeling and analyzing problems that involve decision-making under uncertainty. A high priority will be placed on learning how to choose the appropriate statistics to examine a particular problem, and how to avoid being misled by statistics presented by others that do not appropriately reflect available information.

## Objectives

Students will learn how to use quantitative data and statistical tools to understand problems, how to become smart consumers of statistical reports and quantitative information, and how to communicate statistical findings to a variety of audiences.

## Prerequisites

A thorough understanding of high school algebra and geometry.

# Materials

## Books

**Required:** You will need a core statistics textbook for the class, and there are a few options:

- *Classic Statistics*: Moore, David S., George P. McCabe, Bruce A. Craig. [*Introduction to the Practice of Statistics*](https://www.amazon.com/Introduction-Practice-Statistics-David-Moore/dp/1319013384/). W.H. Freeman and Company. *Any edition 6th or newer is sufficient.*
- *For Public Admin*: Meier, Kenneth, Jeffery Brudney, and John Bohte. [*Applied Statistics for Public and Nonprofit Administration*](https://www.amazon.com/Applied-Statistics-Public-Nonprofit-Administration/dp/1285737237). Cengage. *Any recent edition is fine*
- *Web Option*: Favero, Nathan. [*Statistics Minus the Math: An Introduction for Social Sciences* (https://minusthemath.com)](https://minusthemath.com)

You may find one of these books suits you better than the other. *(I recommend trying each!)* Each book has a slightly different focus. Favero is more focused on a math-light presentation, preferring conceptual explanations, but is light in detail (especially in probability). Moore et al. is a more traditional statistics book (although still applied). Meier et al. is very clearly targeted at Public Administration, but the content itself jumps around a bit relative to the order our presentation of material. If you have strong opinions about any book at the end of the semester, let me know!

**Recommended:** A resource to assist you with Stata usage and coding.

- *Traditional*: Acock, Alan. *Stata: A Gentle Introduction*. Stata Press. Any edition 4th or newer is sufficient.
- *Web Resources*: UCLA Statistical Methods and Data Analytics Stata Learning Modules: <https://stats.oarc.ucla.edu/stata/modules/>

## Software

Stata (any version after 13; the most basic is fine). You can also purchase a student license, which is available for 6- or 12-month intervals, or perpetually. See the Stata website for pricing: <https://www.stata.com/order/new/edu/profplus/student-pricing/>. If you will be taking PAI 722 in the Spring, I recommend a 12-month license ($94). Otherwise, a 6-month subscription is also available ($48). For those of you who do not wish to purchase your own version, copies are located on the computers in the student clusters in the basement of Eggers. You can also access Stata via Syracuse’s remote desktop: <http://rds.syr.edu>. Information on how to log in to the remote desktop is available **[here](https://su-jsm.atlassian.net/wiki/spaces/ITHELP/pages/159941534/Remote+Desktop+Services+RDS)**.

## Hardware

The department will provide a simple scientific calculator on exams for you to use. Graphing calculators are not allowed in exams.

You will need to use a computer to complete assignments in this class. If you do not have one of your own, you may use one on campus. The student clusters in the basement of Eggers are likely the most convenient.

## Online Class Resources

This website hosts the official course syllabus as well as course assignments, problems, and readings. In addition, [Blackboard](http://blackboard.syr.edu) is Syracuse University's course platform. In it, you will find occaisional course announcements, a submission portal for your assignments, and additional materials. In addition, during the semester, solutions to the problem sets and lecture slides will be posted. 

Please note, however, that this is primarily an in-person, not online, class, and as such, class is the primary source of course-related announcements and material.

# Course Requirements

## Overview

Satisfactory completion of the course requires completion of the following:

1. Regular course participation and attendance (10%)
2. Weekly Assignments (20%)
3. Practicum 1 (15%) 
4. Midterm (20%)
5. Practicum 2 (15%)
6. Final (20%)

## Attendance

One of the guiding principles of my class is that you are adults, and thus, capable of managing your own time. I have little interest in policing your lives. Attendance is kept for each day of class, but you will lose no points on attendance if you miss a couple days: everyone has things that occasionally come up in life that need to be dealt with, and I fully realize that some of those things are things you — very understandably — may not want to discuss with your professor. *That's OK!*

That said, attendance in class is an important element to doing well in the course. If you miss more than a couple days, it's advisable to check in. (That way, I also won't mark your attendance grade off for chronic absenteeism.) The easiest way to do this is just email me with a brief reason when something comes up and you have to miss class (which will also allow me to tell you if you're missing anything particularly important).

If you must miss class, the way to make up what you've missed is straightforward: make sure to look over the posted slides, do the reading for the day, get notes from a friend, and still complete the assignment if you are able (or, if it is a day we are going over the assignment, make sure to look over the assignment solutions). If you do these things and still feel like you're missing something, please feel free to come into my office hours and we can talk it through.

::: {.callout-note}
### Participation
There is no formal grade for "participation".  However, I reserve the right to dock a couple points here if you do ridiculous/unprofessional things in class (like answering your cell phone, always coming in late and regularly distracting others, spontaneously breaking out into ribald song in the middle of class, etc).

:::

## Weekly Assignments

There is an assignment each week in class, **due Friday at midnight**.[^friday] Assignments will vary in nature: some will be one-off problem sets, some may build on problem sets from a prior week. All material needed for an assignment will be covered by the Tuesday before the assignment is due, and the assignment itself will be posted no later than Tuesday of the week in question. There is **no penalty** for turning in an assignment up until the Tuesday of the following week.  However, **no assignment work is accepted after class Tuesday of the following week**, as we will go over answers for assignments together in class. There will typically be no assignments on weeks when other significant work (practicums, tests) are due, and students may miss up to two assignments without penalty. Students may also work together on assignments, although each student is ultimately responsible for their own work.

::: {.callout-note}
### Assignment Evaluation
Assignments are evaluated based upon effort and a check completion system. Students who answer every problem will earn a check, with each check worth one point toward their final assignment grade.

:::



::: {.callout-warning}

### Computing
Most homework assignments will be done on a computer using Stata. Do not simply hand in output from Stata. Instead, paste the relevant results into a word processor adding text to explain these results. You must also hand in reproducible script (.do) files with your analysis.  (Don't worry, we'll cover what this means.)

:::


## Practicums

The practicums are, essentially, large assignments that are worth more and graded on a scale.[^pracgrad] They are untimed, take-home, cumulative, and will be completed on your own time (and computer). Unlike the weekly assignments, you are also not allowed to work together on them. Their timing corresponds (roughly) with the midterm and final - you may wish to think of them as the "take-home" midterm and "take-home" final, if you prefer.  

## Midterm and Final

The midterm and final are traditional timed exams given in class on pen and paper.  No computer will be available to you, although you will have access to a calculator. Both exams are cumulative across the course.

# Course Expectations & Guidelines

## Etiquette & Decorum

This is a graduate course: I take it for granted that you have a basic interest in the material, an enthusiastic attitude toward participation, and a respectful attitude to everyone in the room. A university classroom is fundamentally a learning community: be courteous to fellow students and the professor, don’t let yourself be distracted by your cell phone in class, and don’t let what is on your computer screen distract fellow students in the class, either.

## Office & Consultation Hours, Appointments

I encourage you to chat with me at any point if you have questions about the course. You can schedule a meeting with me by going to my website here: <http://jacklreilly.github.io/> and sign up for time at your convenience. You can also always just drop in during my regularly scheduled drop-in office hours without appointment, or stop by to see if my door is open: if it’s open, come on in. (Don’t feel like you’re intruding! I’ll tell you if it’s not a good time.)

## E-mail

Email is the best way to contact me. I'm usually pretty responsive, but as a baseline, I always aim to get back to you in a modified 24-hour fashion: by the end of the business day the day after you email. So if you email me at 2 PM Tuesday, I'll get back to you by 6 PM Wednesday; if 10 PM Thursday, by 6 PM Friday; if you email me at 3 PM on Friday, by 6 PM Monday, etc.[^1]  

::: {.callout-note}
If your email requires a long response, expect me to encourage you to schedule an appointment with me so that we can more effectively discuss your questions.  
:::

[^1]: Again: usually I'm much faster! But if you don't hear from me by this baseline, feel free to bump a reminder.

# Acknowledgments

This course, and this syllabus, consists in large parts of material developed by other professors in the PAI 721 rotation, including, but not limited to, Jun Li, Tomas Olivier, and Ying Shi. I am grateful for their support and permission to use their materials.

[^friday]: Although, I should note, I very much hope you aren't working on my assignments on Friday at 11 PM! I suggest you work on assignments starting on Tuesday of the week in question and finish them early enough so your Friday afternoon and evening isn't overcome with them.
[^pracgrad]: While regular weekly assignments are check/no-check credit, on practicums, you'll receive a certain number of points out of the total.